### ISSUE TITLE
Does not work with our druid installation

### ISSUE THREAD

**Issue by pdeva** [implydata/pivot#46] opened 2015-10-14 16:45 UTC
The UI is stuck on 'loading'
http://screencast.com/t/5HGTLH06RS

I see this msg in the browser console:
http://screencast.com/t/4U66Yadml

**Comment by pdeva** [comment] 2015-10-14 16:47
I am happy to show you our installation privately if that will help debug this issue

**Comment by vogievetsky** [comment] 2015-10-14 17:47
Interesting... let me look into this.

**Comment by vogievetsky** [comment] 2015-10-14 18:50
I think I found the problem. That error happens if one of your measures come back as a `NaN`. Which should not really happen. Even if a `NaN` does happen it should not crash everything like it did for you.

I am going to fix this and release in like an hour or two.

Meanwhile I would also like to determine what was producing those NaNs. I suspect that you were relying on pivot introspection which is a little dumb at this moment (separately I am working on making it smarter). I suspect that pivot was trying to so a SUM(some_hyper_log_log_measure) could you please start pivot again as you did before and see what measures you have selected? Are any of them some sort of fancy sketch or HLL?

This issue will be closed when I fix the NaN thing but please still comment if any of the measures are interesting.

**Comment by pdeva** [comment] 2015-10-14 19:57
This is still present.

Using latest version:

```
root@druid-pivot:/home/prashant# npm list -g imply-pivot
/usr/local/lib
└── imply-pivot@0.4.19 
```

The UI hangs right on hitting the root url. I havent even gotten a chance to add any measures or interact with it at all

**Comment by vogievetsky** [comment] 2015-10-14 22:19
hmmm. ok reopening.

**Comment by pdeva** [comment] 2015-10-14 23:26
if you want I can do a screenshare with you later today to help figure this

**Comment by vogievetsky** [comment] 2015-10-15 04:03
Could we screenshare some time tomorrow (Thursday)? I would love to get this fixed.

**Comment by pdeva** [comment] 2015-10-15 04:04
ok. I can even do right now if you want

On Wednesday, October 14, 2015, Vadim Ogievetsky <notifications@github.com>
wrote:

> Could we screenshare some time tomorrow (Thursday)? I would love to get
> this fixed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/implydata/pivot/issues/46#issuecomment-148275527>.
>


-- 
Prashant

**Comment by vogievetsky** [comment] 2015-10-15 04:39
I can not do today, but let's find a time tomorrow :-)

**Comment by pdeva** [comment] 2015-10-15 18:15
how about now?

**Comment by vogievetsky** [comment] 2015-10-15 18:35
I am ready whenever. Not sure how we should do this... Maybe Google hangouts

**Comment by vogievetsky** [comment] 2015-10-15 18:36
my email is vadim [at] imply.io for hangouts e.t.c

**Comment by pdeva** [comment] 2015-10-15 18:37
i just sent u a hangouts invite.

**Comment by vogievetsky** [comment] 2015-10-15 18:39
trying to connect

**Comment by vogievetsky** [comment] 2015-10-15 18:49
Just to update the thread: @pdeva and I have chatted over hangout and I now understand the issue. This will be fixed today.
Thank you @pdeva

**Comment by pdeva** [comment] 2015-10-17 19:53
waiting for a fix so I can use pivot

**Comment by vogievetsky** [comment] 2015-10-18 02:07
Hi, Sorry I forgot to update this issue. Please try again with the latest pivot. It should not crash on initial load. Going to close the issue for now but if it still crashes I will reopen.

For the best experience you will still want to define your datasources inside the config.yaml auto introspection can only do so much (it will greatly improve in Druid 0.8.2)

**Comment by pdeva** [comment] 2015-10-18 02:12
while 0.4.24 does not crash on initial load, adding just 1 dimension on 'split' caused to throw the same error again.
Screenshot:
http://screencast.com/t/xyY31IvEOs

**Comment by vogievetsky** [comment] 2015-10-19 02:39
Could you try now please. It should no longer crash.
The "Min" and "Max" measures are problematic and should now show `-`.
Could you please tell me more about them? What are they in Druid?
Also log term the solution for you is to define this datasource explicitly in the config.yaml that way the min and max measures can be defined correctly.

**Comment by pdeva** [comment] 2015-10-19 04:04
ok, while it works now, the layout is stil broken.
http://screencast.com/t/PksQuQsQyZ5

a way to resize the column and/or truncate the amount of decimal places might help..

As for min and max, they hold the 'min' and 'max' values of a row respectively.
We sometimes pass Long.MaxValue to min in cases when there is no value.

**Comment by pdeva** [comment] 2015-10-19 04:05
also i see some cells have `0.0.t` as value. what does `t` stand for here?

also you should consider making the 'b' and 'm' capital.

**Comment by vogievetsky** [comment] 2015-10-19 04:52
I am glad to hear that it is finally working, it took some iterations but the code is a lot more robust now.

In the screenshot you sent the layout looks to be behaving as intended, the long numeric values are caused by a pivot misconfiguration.

0.0 t stands for 0.0 trillion. The min and max columns are treated by pivot like sums because there is no way for it (in druid < 0.8.2) to detect what is the underlying agg. Please define them as `$main.min($min)` and `$main.min($max)` in `config.yaml`.

I think making T, B, M capitals is a capital idea.

**Closed by vogievetsky** 2015-10-19 04:52 UTC
Labels: bug, coming soon
