### ISSUE TITLE
Improve Timeseries Chart Hover 

### ISSUE THREAD

**Issue by cheddar** [implydata/pivot#34] opened 2015-10-07 16:06 UTC
I find the timeseries chart hover to be lacking in functionality to the point that I almost want it to just not exist.  But, I really do want it to exist.  What do you think about it operating like:

1. Even if you don't hover over the line, it still generates a hover over the points in the same "plane" on the x-axis
2. Include the actual time in the hover text
3. Provide the "actual" number and then the human readable in parens (something like `1,284,374,372 (1.28b)` )

Am I just totally off-base?

**Comment by asherbitter** [comment] 2015-10-07 17:49
1: Just to clarify, do you mean that you would want it to generate a hover for all measures and not just one?
2: Should be coming soon.
3: Right now it shows the digits the same way it does in the table I believe. Would adding a digit or two everywhere help? Or, would you like a way to have much higher accuracy? Or, do you specifically need the "actual" number?

Anyway, right now out of these #2 is definitely on the roadmap.

**Comment by cheddar** [comment] 2015-10-07 23:13
1. I want all of the points for whatever time point I'm hovering over to show up.  Basically, the fact that I have to find the exact point to hover over is a little annoying.  This isn't super horribad and I hate you for it, it just might be nice to have more of a "proximity" hover.
2. Cool
3. Generally, I'm hovering because I want better accuracy than just the eye-ball I get out of the graph, so I think there is an argument for getting higher accuracy out of the tooltips.  I'm not too adamant about this though.

**Comment by asherbitter** [comment] 2015-10-07 23:39
1. OK sorry but I am still not completely sure so I will ask more clearly. It sounds to me like you want to see the hover info for all measures at once and not just one at a time, but it also sound like there is some problem with the hover bubble not appearing unless you hit a very specific area. If the second thing is correct then it's an unfamiliar bug - there should not be a place within the axes area which does not generate a hover. Please confirm if that's the case.
3. Good point!

**Comment by asherbitter** [comment] 2015-10-07 23:46
(also if you are encountering this bug, then what browser / os are you using?)

**Comment by cheddar** [comment] 2015-10-07 23:50
Chrome on mac.  The only place I get the tooltip to show up is when I hover over the "bend" in the graph.  Well, actually I just noticed that if I hover over that exact point lower down in the graph, it also shows me the tooltip, but if I'm off by even just a little bit, I don't get the tooltip.  This is especially noticeable when aggregating to daily granularity on a weekly chart.  I'd give you a screenshot, but when I take them, my cursor disappears.

**Comment by asherbitter** [comment] 2015-10-07 23:53
Definitely a bug. I can't reproduce right now but we are looking into it.

**Comment by gianm** [comment] 2015-10-14 03:25
+1 on all three things, but especially 1 & 2

**Comment by gianm** [comment] 2015-10-14 03:26
I am having a tough time looking at telemetry-y datasources (where I want to do a lot of time drill down) with the current hover stuff

**Comment by asherbitter** [comment] 2015-10-14 10:02
Update - we have reproduced and figured out the bug in #1, so a fix should be coming soon.

As for #2, it is top priority and should be coming really soon as well.

**Comment by vogievetsky** [comment] 2015-10-14 19:09
@asherbitter on github when you write #1, #2 it auto links them to the issues of that number.

**Comment by vogievetsky** [comment] 2015-10-15 00:31
The PR above addressed 1 and 2. 
As for 3, we are taking it under consideration.
Closing this issue because the core of the problem has been fixed.

![image](https://cloud.githubusercontent.com/assets/177816/10501755/69c63e4e-7299-11e5-9227-b3562f508aee.png)

**Closed by vogievetsky** 2015-10-15 00:31 UTC
Labels: bug, coming soon, incomplete feature, suggestion
